Numpy

In [2]:
# 1 ndarray
import numpy as np

In [2]:
list = [1,2,3,4,5]

a = np.array(list)
print(a)

[1 2 3 4 5]


### 2 创建数组

In [9]:
#### 基础的创建方法
arr = np.array(5) # 创建一个元素为5的数组
arr2 = np.array([1,2,3,4]) # 创建一个元素为1,2,3,4的数组
list = [[1,2,3],[4,5,6]]
arr3 = np.array(list)
print(arr3.ndim) # 获取维度




2


In [13]:
# copy

arr3 = np.array(list)
copy_arr = np.copy(arr3); # 元素和初始的数组相同，但是已经不是一个数组 被定义为深b拷贝
new_arr = arr3;
print ("这是new_arr,修改arr3的值之前",new_arr)
arr3 = np.array([1,2,3])

print ("这是copy_arr",copy_arr)
print ("这是arr3",arr3)
print ("这是new_arr,修改arr3的值之后",new_arr)

这是new_arr,修改arr3的值之前 [[1 2 3]
 [4 5 6]]
这是copy_arr [[1 2 3]
 [4 5 6]]
这是arr3 [1 2 3]
这是new_arr,修改arr3的值之后 [[1 2 3]
 [4 5 6]]


In [ ]:
# 预定义数组
# 全0
all_zeros = np.zeros((2,3),dtype=int)
print (all_zeros)


# 全1
all_ones = np.ones((3,3),dtype=int)
print (all_ones)


In [6]:
# 未初始化
all_empty = np.empty((3,3),dtype=int)

arr_full = np.full((2,3),2,dtype=int)

print (arr_full)

[[2 2 2]
 [2 2 2]]


In [8]:
# like 知识点
# 创建一个和arr_full一样大小的数组，但是元素全为9
arr_full9 = np.full_like(arr_full,9)

print(arr_full9)

[[9 9 9]
 [9 9 9]]


In [ ]:
# 等差数列
arr_arange = np.arange(0,10,2) # 从0到10，步长为2，不包含end
print (arr_arange)


In [ ]:
#等间隔数列

arr_lin = np.linspace(0,10,3) # 从0到10，包含end，3个元素
print(arr_lin)

arr_linspace = np.linspace(0,100,5,dtype=int)
arr_range  = np.arange(0,101,25,dtype=int)

print(arr_new == arr_range)

In [23]:
# 对数间隔
arr_log = np.logspace(0,4,2,base=2)
print (arr_log,arr_log.ndim)



[ 1. 16.] 1



#### 3. 矩阵

In [45]:
# 标量 向量 矩阵
# 解释一下矩阵
# 矩阵是一个二维数组，行和列都是索引，索引从0开始
# 矩阵的元素可以通过索引访问，索引的格式为[行索引,列索引]
arr = np.array([[1,2,3],[4,5,6]])
print (arr)
# 特殊矩阵
print( "0矩阵")
arr_zeros = np.zeros((2,2))
print(arr_zeros)

print("单位矩阵") # 单位矩阵 主对角线上为 1（左上到右下）其他为0
#
arr_1 = np.eye(2,dtype=int)
print(arr_1)

print("对角矩阵") # 只有主对角线上是非零
arr_diag = np.diag([1,2,3])
print(arr_diag)


print("随机数")
arr_rand = np.random.rand(2,2)
print(arr_rand)

# 生成一个指定范围区间得浮点数
print("随机浮点数")
arr = np.random.uniform(0,10,(2,2))
# 生成一个指定范围区间得随机整数
print("随机整数")
arr = np.random.randint(0,10,(2,2))
# 正态分布
# 两边得概率小，中间得概率大
print("正态分布")
arr = np.random.randn(2,2)# -3 ~ 3 之间
print( arr)

print(arr)
print("对称矩阵")
arr_sym = np.tril(arr_diag)
print(arr_sym)


[[1 2 3]
 [4 5 6]]
0矩阵
[[0. 0.]
 [0. 0.]]
单位矩阵
[[1 0]
 [0 1]]
对角矩阵
[[1 0 0]
 [0 2 0]
 [0 0 3]]
随机数
[[0.80887942 0.27520415]
 [0.76192728 0.71665216]]
随机整数
正态分布
[[ 0.24210744 -1.75441114]
 [ 0.46857115 -0.57974743]]
[[ 0.24210744 -1.75441114]
 [ 0.46857115 -0.57974743]]
对称矩阵
[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [52]:
# 设置随机种子
np.random.seed(20)
arr = np.random.randint(1,10 ,(2,5))
print(arr)



[[4 5 7 8 3]
 [1 7 9 6 4]]


In [ ]:
# ndarray 得数据类型
# boolean
arr = np.array([1,2,3,4],dtype=bool)
print(arr)


### 数据索引

In [67]:
# 数据索引以及切片
# 1维数组的切片
arr = np.array([1,2,3,4,5,6,7,8,9])
print(arr[0])
arr = np.random.randint(1,10,(4,5))
print(arr)
print("切片后的",arr[0:2])
# 布尔索引
print ("布尔切片后的",arr[(arr>5)&(arr>6)])

1
[[5 8 1 5 7]
 [3 2 1 6 8]
 [1 5 8 8 5]
 [2 4 6 5 7]]
切片后的 [[5 8 1 5 7]
 [3 2 1 6 8]]
布尔切片后的 [8 7 8 8 8 7]


In [81]:
# 二维数组切片
np.random.seed(20)
arr = np.random.randint(1,100,(4,5))
print(arr)



[[91 16 96 29 91]
 [10 21 76 23 72]
 [35 97 41 86 91]
 [27 84 17 63 17]]


In [84]:
print("索引",arr[2,3]) # 二维数组索引
print("切片",arr[0:2,0:2])
print("获取第二行中的所有数据",arr[1,:])
# 布尔索引
print("布尔切片",arr[(arr>5)])

索引 86
切片 [[91 16]
 [10 21]]
获取第二行中的所有数据 [10 21 76 23 72]
布尔切片 [91 16 96 29 91 10 21 76 23 72 35 97 41 86 91 27 84 17 63 17]


### ndarray的运算



In [88]:
# 算数运算
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
print(a+b) # 加法 对应位置相加
print(a-b) # 减法 对应位置相减
print(a*b) # 乘法 对应位置相乘
print(a/b) # 除法 对应位置相除

[ 6  8 10 12]
[-4 -4 -4 -4]
[ 5 12 21 32]
[0.2        0.33333333 0.42857143 0.5       ]


In [91]:
# 需要注意与python原生的不同
c = [1,2,3,4]
d = [5,6,7,8]
print(c+d)
e = [0,0,0,0]
for i in range(4):
    e[i] = c[i]+d[i]

print (e)

[1, 2, 3, 4, 5, 6, 7, 8]
[6, 8, 10, 12]


In [92]:
# 二维矩阵运算
a = np.array([[1,2],[3,4],[5,6]])
b = np.array([[7,8],[9,10],[11,12]])
print("加法" ,a+b) # 加法 对应位置相加
print("减法" ,a-b) # 减法 对应位置相减
print("乘法" ,a*b) # 乘法 对应位置相乘
print("除法" ,a/b) # 除法 对应位置相除


加法 [[ 8 10]
 [12 14]
 [16 18]]
减法 [[-6 -6]
 [-6 -6]
 [-6 -6]]
乘法 [[ 7 16]
 [27 40]
 [55 72]]
除法 [[0.14285714 0.25      ]
 [0.33333333 0.4       ]
 [0.45454545 0.5       ]]


In [94]:
# 矩阵乘法 矩阵 * 标量

a = 2
b = np.array([[1,2],[3,4],[5,6]])
print("加法",a+b)
print("乘法",a*b)
print("除法",a/b)

加法 [[3 4]
 [5 6]
 [7 8]]
[[ 2  4]
 [ 6  8]
 [10 12]]


In [ ]:
# 矩阵乘法 矩阵 * 矩阵 形状不同
# 广播机制
a = np.array([1,2,3])
b = np.array([[1,2,3],[4,5,6]])
print("a的形状",a.shape,"a的维度",a.ndim)
print("b的形状",b.shape,"b的维度",b.ndim)
print(a*b)

In [ ]:
# 矩阵乘法 矩阵 * 矩阵 形状相同
a= np.array([[1,2,3],[4,5,6], [7,8,9] ])
b = np.array([[1,2,3],[4,5,6],[1,2,3] ])
('a '
 '1 2 3'
 '4 5 6'
 '7 8 9'
 'b'
  '1 2 3'
  '4 5 6'
  '1 2 3')
print(a @ b)
print(np.dot(a,b))

c = np.array([[1,2],
              [3,4]])
d = np.array([[5,6],
              [7,8]])

print(c @ d)
# 验证过程
print([  19, 22 ])
print ([ 43, 50 ])



In [4]:
# Numpy 函数
alist = np.array(['广','阔','天','地'])
blist = np.array(['大','有','作','为'])

print(alist)

['广' '阔' '天' '地']


## 2 统计函数
求和 计算平均值 计算中位数 标准差 方差
查找最大值 最小值
计算分位数 累积和 累计差


In [7]:
# arr = np.array([1,2,3,4,5,6,7,8,9])
# 数据准备
np.random.seed(20)
arr = np.random.randint(1,10,9)
print(arr)

[4 5 7 8 3 1 7 9 6]


In [8]:
# 求和
print(np.sum(arr))

50
